server:
  port: 8888

spring:
  application:
    name: sansam's work

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always

  redis:
    host: 118.25.210.217
    port: 13379
    password: password123456
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 10
